"""icon_sc.core — model-agnostic composition framework.

Curated public API re-exports (S02: state layer + contracts; S03: component
taxonomy + wrappers + context + T0 driver/monitors). Keeping the namespace-level
``ICON-sc`` package implicit (PEP 420) is what lets ``icon-sc-icon`` and
``icon-sc-bridges`` install into the same import root.
"""

from icon_sc.core.components import (
    CallingFrequency,
    Component,
    ComponentWrapper,
    DiagnosticComponent,
    DynamicalCore,
    ImplicitTendencyComponent,
    Monitor,
    OutputSchema,
    ScalingWrapper,
    Stepper,
    Subcycle,
    TendencyComponent,
)
from icon_sc.core.config import Config, provenance_stamp
from icon_sc.core.context import Allocator, ComputeContext
from icon_sc.core.contracts import (
    ContractViolation,
    ContractViolationError,
    ConversionError,
    ConversionPlan,
    ConversionStep,
    Differentiable,
    DynamicChecker,
    EgressPlan,
    FieldSchema,
    HaloPolicy,
    IngressPlan,
    PropertyDictError,
    PropertySpec,
    StateSchema,
    StaticChecker,
    apply_conversion_plan,
    parse_properties,
)
from icon_sc.core.coupling import (
    SSUS,
    BusError,
    ConcurrentCoupling,
    CouplingConstraintError,
    CouplingConstraints,
    ParallelSplitting,
    SequentialTendencySplitting,
    SequentialTendencyStepper,
    SequentialUpdateSplitting,
    SlowTendencyBus,
    TendencySlot,
    TendencyStepper,
    constraints_of,
    dict_axpy,
    dict_fma,
    validate_composition,
)
from icon_sc.core.driver import timeloop
from icon_sc.core.ingress import Backend, make_backend
from icon_sc.core.io import MemoryMonitor, NetCDFMonitor
from icon_sc.core.plan import (
    ExecutionPlan,
    PlanBuilder,
    PlanCompileError,
    PlanDriftError,
    StalePlanError,
    renegotiate_and_diff,
)
from icon_sc.core.profiling import Timer
from icon_sc.core.registry import Factory, MetaFactory, RegistrationError
from icon_sc.core.state import (
    NamesRegistryError,
    QuantityDef,
    StateVault,
    UnitsError,
    canonical_units,
    convert_array,
    make_dataarray,
    register_quantity,
    units_identical,
    verify_noop,
)
from icon_sc.core.typing import FieldBuffer, HaloState, Location

__version__ = "0.1.0"

__all__ = [
    "SSUS",
    "Allocator",
    "Backend",
    "BusError",
    "CallingFrequency",
    "Component",
    "ComponentWrapper",
    "ComputeContext",
    "ConcurrentCoupling",
    "Config",
    "ContractViolation",
    "ContractViolationError",
    "ConversionError",
    "ConversionPlan",
    "ConversionStep",
    "CouplingConstraintError",
    "CouplingConstraints",
    "DiagnosticComponent",
    "Differentiable",
    "DynamicChecker",
    "DynamicalCore",
    "EgressPlan",
    "ExecutionPlan",
    "Factory",
    "FieldBuffer",
    "FieldSchema",
    "HaloPolicy",
    "HaloState",
    "ImplicitTendencyComponent",
    "IngressPlan",
    "Location",
    "MemoryMonitor",
    "MetaFactory",
    "Monitor",
    "NamesRegistryError",
    "NetCDFMonitor",
    "OutputSchema",
    "ParallelSplitting",
    "PlanBuilder",
    "PlanCompileError",
    "PlanDriftError",
    "PropertyDictError",
    "PropertySpec",
    "QuantityDef",
    "RegistrationError",
    "ScalingWrapper",
    "SequentialTendencySplitting",
    "SequentialTendencyStepper",
    "SequentialUpdateSplitting",
    "SlowTendencyBus",
    "StalePlanError",
    "StateSchema",
    "StateVault",
    "StaticChecker",
    "Stepper",
    "Subcycle",
    "TendencyComponent",
    "TendencySlot",
    "TendencyStepper",
    "Timer",
    "UnitsError",
    "apply_conversion_plan",
    "canonical_units",
    "constraints_of",
    "convert_array",
    "dict_axpy",
    "dict_fma",
    "make_backend",
    "make_dataarray",
    "parse_properties",
    "provenance_stamp",
    "register_quantity",
    "renegotiate_and_diff",
    "timeloop",
    "units_identical",
    "validate_composition",
    "verify_noop",
]
